INSERT INTO users (name, location, email) VALUES
('Emma Williams', 'Chicago, IL', 'emma.williams@example.com'),
('Liam Anderson', 'Houston, TX', 'liam.anderson@example.com'),
('Sophia Martinez', 'Phoenix, AZ', 'sophia.martinez@example.com'),
('Noah Thompson', 'Philadelphia, PA', 'noah.thompson@example.com'),
('Olivia Garcia', 'San Antonio, TX', 'olivia.garcia@example.com'),
('Ethan Davis', 'San Diego, CA', 'ethan.davis@example.com'),
('Ava Wilson', 'Dallas, TX', 'ava.wilson@example.com'),
('Mason Taylor', 'San Jose, CA', 'mason.taylor@example.com'),
('Isabella Moore', 'Austin, TX', 'isabella.moore@example.com'),
('James Jackson', 'Jacksonville, FL', 'james.jackson@example.com'),
('Mia White', 'Fort Worth, TX', 'mia.white@example.com'),
('Benjamin Harris', 'Columbus, OH', 'benjamin.harris@example.com'),
('Charlotte Clark', 'Charlotte, NC', 'charlotte.clark@example.com'),
('Elijah Lewis', 'San Francisco, CA', 'elijah.lewis@example.com'),
('Amelia Robinson', 'Indianapolis, IN', 'amelia.robinson@example.com'),
('Logan Walker', 'Seattle, WA', 'logan.walker@example.com'),
('Harper Hall', 'Denver, CO', 'harper.hall@example.com'),
('Lucas Allen', 'Nashville, TN', 'lucas.allen@example.com'),
('Evelyn Young', 'Oklahoma City, OK', 'evelyn.young@example.com'),
('Henry Hernandez', 'El Paso, TX', 'henry.hernandez@example.com'),
('Abigail King', 'Washington, DC', 'abigail.king@example.com'),
('Alexander Wright', 'Las Vegas, NV', 'alexander.wright@example.com'),
('Emily Lopez', 'Louisville, KY', 'emily.lopez@example.com'),
('Sebastian Hill', 'Portland, OR', 'sebastian.hill@example.com'),
('Elizabeth Scott', 'Memphis, TN', 'elizabeth.scott@example.com'),
('Jack Green', 'Baltimore, MD', 'jack.green@example.com'),
('Sofia Adams', 'Milwaukee, WI', 'sofia.adams@example.com'),
('Owen Baker', 'Albuquerque, NM', 'owen.baker@example.com'),
('Avery Nelson', 'Tucson, AZ', 'avery.nelson@example.com'),
('Aiden Carter', 'Fresno, CA', 'aiden.carter@example.com'),
('Ella Mitchell', 'Sacramento, CA', 'ella.mitchell@example.com'),
('Daniel Perez', 'Mesa, AZ', 'daniel.perez@example.com'),
('Scarlett Roberts', 'Kansas City, MO', 'scarlett.roberts@example.com'),
('Matthew Turner', 'Atlanta, GA', 'matthew.turner@example.com'),
('Grace Phillips', 'Omaha, NE', 'grace.phillips@example.com'),
('Jayden Campbell', 'Colorado Springs, CO', 'jayden.campbell@example.com'),
('Chloe Parker', 'Raleigh, NC', 'chloe.parker@example.com'),
('Michael Evans', 'Long Beach, CA', 'michael.evans@example.com'),
('Penelope Edwards', 'Virginia Beach, VA', 'penelope.edwards@example.com'),
('David Collins', 'Minneapolis, MN', 'david.collins@example.com'),
('Riley Stewart', 'Tampa, FL', 'riley.stewart@example.com'),
('Carter Morris', 'New Orleans, LA', 'carter.morris@example.com'),
('Zoey Sanchez', 'Arlington, TX', 'zoey.sanchez@example.com'),
('Wyatt Rogers', 'Wichita, KS', 'wyatt.rogers@example.com'),
('Nora Reed', 'Bakersfield, CA', 'nora.reed@example.com'),
('John Cook', 'Aurora, CO', 'john.cook@example.com'),
('Lily Morgan', 'Anaheim, CA', 'lily.morgan@example.com'),
('Luke Bell', 'Santa Ana, CA', 'luke.bell@example.com'),
('Hannah Murphy', 'Corpus Christi, TX', 'hannah.murphy@example.com'),
('Gabriel Bailey', 'Riverside, CA', 'gabriel.bailey@example.com'),
('Addison Rivera', 'St. Louis, MO', 'addison.rivera@example.com'),
('Anthony Cooper', 'Lexington, KY', 'anthony.cooper@example.com'),
('Leah Richardson', 'Pittsburgh, PA', 'leah.richardson@example.com'),
('Isaac Cox', 'Stockton, CA', 'isaac.cox@example.com'),
('Zoe Howard', 'Anchorage, AK', 'zoe.howard@example.com'),
('Dylan Ward', 'Cincinnati, OH', 'dylan.ward@example.com'),
('Natalie Torres', 'St. Paul, MN', 'natalie.torres@example.com'),
('Andrew Peterson', 'Toledo, OH', 'andrew.peterson@example.com'),
('Victoria Gray', 'Greensboro, NC', 'victoria.gray@example.com'),
('Christopher Ramirez', 'Newark, NJ', 'christopher.ramirez@example.com'),
('Brooklyn James', 'Plano, TX', 'brooklyn.james@example.com'),
('Jaxon Watson', 'Henderson, NV', 'jaxon.watson@example.com'),
('Samantha Brooks', 'Lincoln, NE', 'samantha.brooks@example.com'),
('Lincoln Kelly', 'Buffalo, NY', 'lincoln.kelly@example.com'),
('Aubrey Sanders', 'Fort Wayne, IN', 'aubrey.sanders@example.com'),
('Joshua Price', 'Jersey City, NJ', 'joshua.price@example.com'),
('Stella Bennett', 'Chula Vista, CA', 'stella.bennett@example.com'),
('Samuel Wood', 'Orlando, FL', 'samuel.wood@example.com'),
('Hazel Barnes', 'St. Petersburg, FL', 'hazel.barnes@example.com'),
('Joseph Ross', 'Norfolk, VA', 'joseph.ross@example.com'),
('Savannah Henderson', 'Chandler, AZ', 'savannah.henderson@example.com'),
('Ryan Coleman', 'Laredo, TX', 'ryan.coleman@example.com'),
('Anna Jenkins', 'Madison, WI', 'anna.jenkins@example.com'),
('Nathan Perry', 'Durham, NC', 'nathan.perry@example.com'),
('Layla Powell', 'Lubbock, TX', 'layla.powell@example.com'),
('Aaron Long', 'Winston-Salem, NC', 'aaron.long@example.com'),
('Violet Patterson', 'Garland, TX', 'violet.patterson@example.com'),
('Isaiah Hughes', 'Glendale, AZ', 'isaiah.hughes@example.com'),
('Claire Flores', 'Hialeah, FL', 'claire.flores@example.com'),
('Caleb Washington', 'Reno, NV', 'caleb.washington@example.com'),
('Audrey Butler', 'Baton Rouge, LA', 'audrey.butler@example.com'),
('Julian Simmons', 'Irvine, CA', 'julian.simmons@example.com'),
('Eleanor Foster', 'Scottsdale, AZ', 'eleanor.foster@example.com'),
('Eli Gonzales', 'North Las Vegas, NV', 'eli.gonzales@example.com'),
('Leila Bryant', 'Irving, TX', 'leila.bryant@example.com'),
('Levi Alexander', 'Fremont, CA', 'levi.alexander@example.com'),
('Naomi Russell', 'Birmingham, AL', 'naomi.russell@example.com'),
('Sebastian Griffin', 'Rochester, NY', 'sebastian.griffin@example.com'),
('Maya Diaz', 'San Bernardino, CA', 'maya.diaz@example.com'),
('Ezra Hayes', 'Spokane, WA', 'ezra.hayes@example.com'),
('Paisley Myers', 'Gilbert, AZ', 'paisley.myers@example.com'),
('Grayson Ford', 'Des Moines, IA', 'grayson.ford@example.com'),
('Piper Hamilton', 'Montgomery, AL', 'piper.hamilton@example.com'),
('Leo Graham', 'Richmond, VA', 'leo.graham@example.com'),
('Willow Sullivan', 'Tacoma, WA', 'willow.sullivan@example.com'),
('Nolan Wallace', 'Providence, RI', 'nolan.wallace@example.com'),
('Skylar West', 'Salt Lake City, UT', 'skylar.west@example.com'),
('Colton Cole', 'Little Rock, AR', 'colton.cole@example.com'),
('Autumn Shaw', 'Huntington Beach, CA', 'autumn.shaw@example.com'),
('Micah Mendez', 'Columbus, GA', 'micah.mendez@example.com'),
('Jade Morrison', 'Spokane Valley, WA', 'jade.morrison@example.com'),
('Finn OBrien', 'Portland, ME', 'finn.obrien@example.com'),
('Aria Patel', 'Sunnyvale, CA', 'aria.patel@example.com'),
('Declan Murphy', 'Dublin, Ireland', 'declan.murphy@example.com');
